export const SELF_LOGIN = 'SELF_LOGIN'
export const SELF_LOGIN_SUCCESS = 'SELF_LOGIN_SUCCESS'

export const STORIES_LATEST_FETCH = 'STORIES_LATEST_FETCH'
export const STORIES_LATEST_FETCH_SUCCESS = 'STORIES_LATEST_FETCH_SUCCESS'
